### ISSUE TITLE
Hot module reload

### ISSUE THREAD

**Issue by jeroenhouben** [odiumediae/webpacker#4]
Hi and thanks for your example project,

Do you know how to enable hot module reloading? All webpack / phoenix tutorials I found have phoenix reload the entire page, whereas with WP you can have just the css be reloaded. Which is nice when you're working styling something like form wizards where you don't want to click through all the steps only to find out you saving your css file just reloaded the page and cleared the form :)

**Comment by odiumediae** [comment]
Hi, @jeroenhouben!

Sorry for the extremely long wainting time. I've been very busy for a while, but I forgot to re-enable GitHub notifications afterwards, so I didn't notice the issues that accumulated, my bad.

There is an easy solution for the problem. I'll explain it in detail, not to be condescending (you seem like an experienced fella), but to help others who might have the same problem in the future.

In the `config/dev.exs` file in your projects root folder is still set up as per default. That means Phoenix will still automatically reload when files with certain types are changed:

```
config :app, AppWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/app_web/views/.*(ex)$},
      ~r{lib/app_web/templates/.*(eex)$}
    ]
]
```

As you can see, files with the following extensions will still trigger a reload: `js|css|png|jpeg|jpg|gif|svg`

You can remove the extensions you want to handle yourself, for example `js` and `css`, and hot reloading will work nicely for these files, because Phoenix won't meddle anymore.

Once again, sorry for the long response time, and I hope this helps, even if you've already found the solution yourself by now.

**Comment by jeroenhouben** [comment]
> Once again, sorry for the long response time

Not at all necessary :) Thanks for your kind reply. I figured it out in the meantime, oddly it now works with this line still intact:

```
~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
```

**Comment by odiumediae** [comment]
@jeroenhouben Oh, that's interesting – how did you achieve that?
