### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alchemistsaint** [odiumediae/webpacker#5]
Hi, Why i'm getting this error?

[error] Task #PID<0.367.0> started from AppWeb.Endpoint terminating
** (stop) :watcher_command_error
    (phoenix) lib/phoenix/endpoint/watcher.ex:29: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["node", ["node_modules/.bin/webpack-dev-server", "--inline", "--colors", "--hot", "--stdin", "--host", "localhost"
, "--port", "8080", "--public", "localhost:8080"], [cd: "c:/xampp/htdocs/webpacker/assets"]]

c:\xampp\htdocs\webpacker\assets\node_modules\.bin\webpack-dev-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3

**Comment by odiumediae** [comment]
Apparently you're using a Windows OS. Since the error m,essage complains about a wrong path or missing file, I'd suggest to start watching your directory divider, i.e. slashes: `/` versus backslashes: `\`. Windows operating systems use backslashes as directory dividers in paths, whereas Unix based systems use slashes.

In the error messages you quoted above, you'll see two different directory dividers for for Windows paths: `c:/xampp/htdocs/webpacker/assets` and `c:\xampp\htdocs\webpacker\assets\node_modules.bin\webpack-dev-server`. The first one is obviously using the wrong directory divider, probably due to how the path is set in the config.

You could try two things:

1. In `c:\[your project folder]\config\dev.exs` change the path `node_modules/.bin/webpack-dev-server` to use backsalshes instead of slashes, like this: `node_modules\.bin\webpack-dev-server`

2. Install webpack-dev-server globally (`npm install -g webpack-dev-server`) and replace the path `node_modules/.bin/webpack-dev-server`  with `webpack-dev-server`

Try (1) first, because installing npm modules globally should be avoided, if possible. Also, since I have virtually no experience with developing under Windows operating systems, the `.bin` directory in the path might also be a problem (because it begins with a dot).

I hope that helped, and sorry for the long responding time. I was very busy for a while and forgot to re-enable GitHub notifications, so I have missed that new issues have been filed. My bad.
